
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "EntidadRepetidaException", targetNamespace = "http://webservices/")
public class EntidadRepetidaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EntidadRepetidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EntidadRepetidaException_Exception(String message, EntidadRepetidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public EntidadRepetidaException_Exception(String message, EntidadRepetidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.EntidadRepetidaException
     */
    public EntidadRepetidaException getFaultInfo() {
        return faultInfo;
    }

}
