
package webservices;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "MaximoDeTuristasAlcanzadoException", targetNamespace = "http://webservices/")
public class MaximoDeTuristasAlcanzadoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MaximoDeTuristasAlcanzadoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MaximoDeTuristasAlcanzadoException_Exception(String message, MaximoDeTuristasAlcanzadoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public MaximoDeTuristasAlcanzadoException_Exception(String message, MaximoDeTuristasAlcanzadoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.MaximoDeTuristasAlcanzadoException
     */
    public MaximoDeTuristasAlcanzadoException getFaultInfo() {
        return faultInfo;
    }

}
