
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorCargaDatos", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PublicadorCargaDatos {


    /**
     * 
     */
    @WebMethod
    @Action(input = "http://webservices/PublicadorCargaDatos/cargarDatosRequest", output = "http://webservices/PublicadorCargaDatos/cargarDatosResponse")
    public void cargarDatos();

}
