
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorCargaDatosService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/webservices/CargaDatos?wsdl")
public class PublicadorCargaDatosService
    extends Service
{

    private final static URL PUBLICADORCARGADATOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCARGADATOSSERVICE_EXCEPTION;
    private final static QName PUBLICADORCARGADATOSSERVICE_QNAME = new QName("http://webservices/", "PublicadorCargaDatosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/webservices/CargaDatos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCARGADATOSSERVICE_WSDL_LOCATION = url;
        PUBLICADORCARGADATOSSERVICE_EXCEPTION = e;
    }

    public PublicadorCargaDatosService() {
        super(__getWsdlLocation(), PUBLICADORCARGADATOSSERVICE_QNAME);
    }

    public PublicadorCargaDatosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCARGADATOSSERVICE_QNAME, features);
    }

    public PublicadorCargaDatosService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCARGADATOSSERVICE_QNAME);
    }

    public PublicadorCargaDatosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCARGADATOSSERVICE_QNAME, features);
    }

    public PublicadorCargaDatosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorCargaDatosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorCargaDatos
     */
    @WebEndpoint(name = "PublicadorCargaDatosPort")
    public PublicadorCargaDatos getPublicadorCargaDatosPort() {
        return super.getPort(new QName("http://webservices/", "PublicadorCargaDatosPort"), PublicadorCargaDatos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorCargaDatos
     */
    @WebEndpoint(name = "PublicadorCargaDatosPort")
    public PublicadorCargaDatos getPublicadorCargaDatosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "PublicadorCargaDatosPort"), PublicadorCargaDatos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCARGADATOSSERVICE_EXCEPTION!= null) {
            throw PUBLICADORCARGADATOSSERVICE_EXCEPTION;
        }
        return PUBLICADORCARGADATOSSERVICE_WSDL_LOCATION;
    }

}
