
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorControladorImagenesService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/webservices/ControladorImagenes?wsdl")
public class PublicadorControladorImagenesService
    extends Service
{

    private final static URL PUBLICADORCONTROLADORIMAGENESSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCONTROLADORIMAGENESSERVICE_EXCEPTION;
    private final static QName PUBLICADORCONTROLADORIMAGENESSERVICE_QNAME = new QName("http://webservices/", "PublicadorControladorImagenesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/webservices/ControladorImagenes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONTROLADORIMAGENESSERVICE_WSDL_LOCATION = url;
        PUBLICADORCONTROLADORIMAGENESSERVICE_EXCEPTION = e;
    }

    public PublicadorControladorImagenesService() {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORIMAGENESSERVICE_QNAME);
    }

    public PublicadorControladorImagenesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORIMAGENESSERVICE_QNAME, features);
    }

    public PublicadorControladorImagenesService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONTROLADORIMAGENESSERVICE_QNAME);
    }

    public PublicadorControladorImagenesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONTROLADORIMAGENESSERVICE_QNAME, features);
    }

    public PublicadorControladorImagenesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorControladorImagenesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorControladorImagenes
     */
    @WebEndpoint(name = "PublicadorControladorImagenesPort")
    public PublicadorControladorImagenes getPublicadorControladorImagenesPort() {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorImagenesPort"), PublicadorControladorImagenes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorControladorImagenes
     */
    @WebEndpoint(name = "PublicadorControladorImagenesPort")
    public PublicadorControladorImagenes getPublicadorControladorImagenesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorImagenesPort"), PublicadorControladorImagenes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONTROLADORIMAGENESSERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONTROLADORIMAGENESSERVICE_EXCEPTION;
        }
        return PUBLICADORCONTROLADORIMAGENESSERVICE_WSDL_LOCATION;
    }

}
