
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorControladorUsuarioService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/webservices/ControladorUsuario?wsdl")
public class PublicadorControladorUsuarioService
    extends Service
{

    private final static URL PUBLICADORCONTROLADORUSUARIOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCONTROLADORUSUARIOSERVICE_EXCEPTION;
    private final static QName PUBLICADORCONTROLADORUSUARIOSERVICE_QNAME = new QName("http://webservices/", "PublicadorControladorUsuarioService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/webservices/ControladorUsuario?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONTROLADORUSUARIOSERVICE_WSDL_LOCATION = url;
        PUBLICADORCONTROLADORUSUARIOSERVICE_EXCEPTION = e;
    }

    public PublicadorControladorUsuarioService() {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORUSUARIOSERVICE_QNAME);
    }

    public PublicadorControladorUsuarioService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORUSUARIOSERVICE_QNAME, features);
    }

    public PublicadorControladorUsuarioService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONTROLADORUSUARIOSERVICE_QNAME);
    }

    public PublicadorControladorUsuarioService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONTROLADORUSUARIOSERVICE_QNAME, features);
    }

    public PublicadorControladorUsuarioService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorControladorUsuarioService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorControladorUsuario
     */
    @WebEndpoint(name = "PublicadorControladorUsuarioPort")
    public PublicadorControladorUsuario getPublicadorControladorUsuarioPort() {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorUsuarioPort"), PublicadorControladorUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorControladorUsuario
     */
    @WebEndpoint(name = "PublicadorControladorUsuarioPort")
    public PublicadorControladorUsuario getPublicadorControladorUsuarioPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorUsuarioPort"), PublicadorControladorUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONTROLADORUSUARIOSERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONTROLADORUSUARIOSERVICE_EXCEPTION;
        }
        return PUBLICADORCONTROLADORUSUARIOSERVICE_WSDL_LOCATION;
    }

}
