
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorControladorActividadService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/webservices/ControladorActividad?wsdl")
public class PublicadorControladorActividadService
    extends Service
{

    private final static URL PUBLICADORCONTROLADORACTIVIDADSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCONTROLADORACTIVIDADSERVICE_EXCEPTION;
    private final static QName PUBLICADORCONTROLADORACTIVIDADSERVICE_QNAME = new QName("http://webservices/", "PublicadorControladorActividadService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/webservices/ControladorActividad?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONTROLADORACTIVIDADSERVICE_WSDL_LOCATION = url;
        PUBLICADORCONTROLADORACTIVIDADSERVICE_EXCEPTION = e;
    }

    public PublicadorControladorActividadService() {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORACTIVIDADSERVICE_QNAME);
    }

    public PublicadorControladorActividadService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORACTIVIDADSERVICE_QNAME, features);
    }

    public PublicadorControladorActividadService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONTROLADORACTIVIDADSERVICE_QNAME);
    }

    public PublicadorControladorActividadService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONTROLADORACTIVIDADSERVICE_QNAME, features);
    }

    public PublicadorControladorActividadService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorControladorActividadService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorControladorActividad
     */
    @WebEndpoint(name = "PublicadorControladorActividadPort")
    public PublicadorControladorActividad getPublicadorControladorActividadPort() {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorActividadPort"), PublicadorControladorActividad.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorControladorActividad
     */
    @WebEndpoint(name = "PublicadorControladorActividadPort")
    public PublicadorControladorActividad getPublicadorControladorActividadPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorActividadPort"), PublicadorControladorActividad.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONTROLADORACTIVIDADSERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONTROLADORACTIVIDADSERVICE_EXCEPTION;
        }
        return PUBLICADORCONTROLADORACTIVIDADSERVICE_WSDL_LOCATION;
    }

}
