
package webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.ws.Action;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PublicadorControladorImagenes", targetNamespace = "http://webservices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface PublicadorControladorImagenes {


    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/PublicadorControladorImagenes/almacenarImagenUsuarioRequest", output = "http://webservices/PublicadorControladorImagenes/almacenarImagenUsuarioResponse")
    public String almacenarImagenUsuario(
        @WebParam(name = "arg0", partName = "arg0")
        byte[] arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/PublicadorControladorImagenes/almacenarImagenActividadRequest", output = "http://webservices/PublicadorControladorImagenes/almacenarImagenActividadResponse")
    public String almacenarImagenActividad(
        @WebParam(name = "arg0", partName = "arg0")
        byte[] arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/PublicadorControladorImagenes/almacenarImagenPaqueteRequest", output = "http://webservices/PublicadorControladorImagenes/almacenarImagenPaqueteResponse")
    public String almacenarImagenPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        byte[] arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @param arg1
     * @param arg2
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/PublicadorControladorImagenes/almacenarImagenSalidaRequest", output = "http://webservices/PublicadorControladorImagenes/almacenarImagenSalidaResponse")
    public String almacenarImagenSalida(
        @WebParam(name = "arg0", partName = "arg0")
        byte[] arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://webservices/PublicadorControladorImagenes/obtenerImagenRequest", output = "http://webservices/PublicadorControladorImagenes/obtenerImagenResponse")
    public byte[] obtenerImagen(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
