
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorControladorSalidaService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/webservices/ControladorSalida?wsdl")
public class PublicadorControladorSalidaService
    extends Service
{

    private final static URL PUBLICADORCONTROLADORSALIDASERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCONTROLADORSALIDASERVICE_EXCEPTION;
    private final static QName PUBLICADORCONTROLADORSALIDASERVICE_QNAME = new QName("http://webservices/", "PublicadorControladorSalidaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/webservices/ControladorSalida?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONTROLADORSALIDASERVICE_WSDL_LOCATION = url;
        PUBLICADORCONTROLADORSALIDASERVICE_EXCEPTION = e;
    }

    public PublicadorControladorSalidaService() {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORSALIDASERVICE_QNAME);
    }

    public PublicadorControladorSalidaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORSALIDASERVICE_QNAME, features);
    }

    public PublicadorControladorSalidaService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONTROLADORSALIDASERVICE_QNAME);
    }

    public PublicadorControladorSalidaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONTROLADORSALIDASERVICE_QNAME, features);
    }

    public PublicadorControladorSalidaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorControladorSalidaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorControladorSalida
     */
    @WebEndpoint(name = "PublicadorControladorSalidaPort")
    public PublicadorControladorSalida getPublicadorControladorSalidaPort() {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorSalidaPort"), PublicadorControladorSalida.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorControladorSalida
     */
    @WebEndpoint(name = "PublicadorControladorSalidaPort")
    public PublicadorControladorSalida getPublicadorControladorSalidaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorSalidaPort"), PublicadorControladorSalida.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONTROLADORSALIDASERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONTROLADORSALIDASERVICE_EXCEPTION;
        }
        return PUBLICADORCONTROLADORSALIDASERVICE_WSDL_LOCATION;
    }

}
