
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PublicadorControladorDepartamentoService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:9128/webservices/ControladorDepartamento?wsdl")
public class PublicadorControladorDepartamentoService
    extends Service
{

    private final static URL PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_EXCEPTION;
    private final static QName PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_QNAME = new QName("http://webservices/", "PublicadorControladorDepartamentoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9128/webservices/ControladorDepartamento?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_WSDL_LOCATION = url;
        PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_EXCEPTION = e;
    }

    public PublicadorControladorDepartamentoService() {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_QNAME);
    }

    public PublicadorControladorDepartamentoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_QNAME, features);
    }

    public PublicadorControladorDepartamentoService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_QNAME);
    }

    public PublicadorControladorDepartamentoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_QNAME, features);
    }

    public PublicadorControladorDepartamentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicadorControladorDepartamentoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicadorControladorDepartamento
     */
    @WebEndpoint(name = "PublicadorControladorDepartamentoPort")
    public PublicadorControladorDepartamento getPublicadorControladorDepartamentoPort() {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorDepartamentoPort"), PublicadorControladorDepartamento.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicadorControladorDepartamento
     */
    @WebEndpoint(name = "PublicadorControladorDepartamentoPort")
    public PublicadorControladorDepartamento getPublicadorControladorDepartamentoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "PublicadorControladorDepartamentoPort"), PublicadorControladorDepartamento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_EXCEPTION!= null) {
            throw PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_EXCEPTION;
        }
        return PUBLICADORCONTROLADORDEPARTAMENTOSERVICE_WSDL_LOCATION;
    }

}
